// Generated by https://quicktype.io

// Interface con atributos que contiene API
export interface PokemonListResponse {
    count:    number;
    // '?' permite que sea opcional el atributo en el tipado de TS
    next?:     string;
    previous?: string;
    results:  SmallPokemon[];
}

// Atributos de 'SmallPokemon' agregando los requeridos
export interface SmallPokemon {
    name: string;
    url:  string;
    id: number;
    img: string;
}
